---
title: "Dicentrics curve fitting report"
author: "`r paste('Biodose Tools', '-', utils::packageVersion(pkg = 'biodosetools'))`"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: word_document
params:
  fit_results_list: NA
---

```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(rhandsontable)
pander::panderOptions("table.style", "grid")
```

```{r load-data, echo=FALSE}
count_data <- params$fit_results_list[["fit_raw_data"]]
fit_model_statistics <- params$fit_results_list[["fit_model_statistics"]]
fit_model_summary <- params$fit_results_list[["fit_model_summary"]]
fit_coeffs <- params$fit_results_list[["fit_coeffs"]]
fit_var_cov_mat <- params$fit_results_list[["fit_var_cov_mat"]]
fit_cor_mat <- params$fit_results_list[["fit_cor_mat"]]
fit_formula_tex <- params$fit_results_list[["fit_formula_tex"]]
gg_curve <- params$fit_results_list[["gg_curve"]]
# detection_lims <- params$fit_results_list[["detection_lims"]]
```

## Count data used
```{r echo=FALSE}
count_data %>%
  dplyr::rename(`D (Gy)` = D) %>%
  pander::pander()
# TODO:  hot_col(c(1), format = "0.000", colWidths = 60)
# TODO: Add u-value highlighting
```

## Results

### Fit formula
```{r echo=FALSE}
withMathJax(paste0("$$", fit_formula_tex, "$$"))
```

### Model
`r fit_model_summary`

### Coefficients
```{r echo=FALSE}
fit_coeffs %>%
  formatC(format = "e", digits = 3) %>%
  # as.data.frame() %>%
  # dplyr::select(-statistic) %>%
  # as.matrix() %>%
  pander::pander()
```

### Model-level statistics
```{r echo=FALSE}
fit_model_statistics %>%
  pander::pander()
```

### Correlation matrix
```{r echo=FALSE}
fit_cor_mat %>%
  formatC(format = "f", digits = 3) %>%
  pander::pander()
```

### Variance-covariance matrix
```{r echo=FALSE}
fit_var_cov_mat %>%
  formatC(format = "e", digits = 3) %>%
  pander::pander()
```

<!-- ### Detection limits -->
<!-- ```{r echo=FALSE} -->
<!-- detection_lims %>% -->
<!--   `colnames<-`(c("N", "X95", "D (mGy)", "X83", "D (mGy)")) %>%  -->
<!--   pander::pander() -->
<!--   # TODO: hot_col(c(3, 5), format = "0.00", colWidths = 75)  -->
<!-- ``` -->

### Curve plot
```{r echo=FALSE}
gg_curve
```

### Download fit results
The DOCX format does not support embedded files. You can only save the results in RDS format from Biodose Tools or from the HTML report.
