---
title: "Curve fitting report"
author: "`r paste('Biodose Tools', '-', utils::packageVersion(pkg = 'biodosetools'))`"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: 
  # prettydoc::html_pretty:
    # theme: cayman
  html_document:
    theme: cosmo
    # css: style.css
params:
  fit_results_list: NA
---

```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(rhandsontable)
xfun::pkg_load2(c("base64enc", "htmltools", "mime"))
```

```{r include=FALSE}
embed_var <- function(x, ...) {
  # f = tempfile(fileext = '.rds')
  f <- paste("fitting-data-", Sys.Date(), ".rds", sep = "")
  saveRDS(x, f)
  xfun::embed_file(f, ...)
}
```

```{r load-data, echo=FALSE}
count_data <- params$fit_results_list[["fit_raw_data"]]
fit_model_statistics <- params$fit_results_list[["fit_model_statistics"]]
fit_model_summary <- params$fit_results_list[["fit_model_summary"]]
fit_coeffs <- params$fit_results_list[["fit_coeffs"]]
fit_var_cov_mat <- params$fit_results_list[["fit_var_cov_mat"]]
fit_cor_mat <- params$fit_results_list[["fit_cor_mat"]]
fit_formula_tex <- params$fit_results_list[["fit_formula_tex"]]
gg_curve <- params$fit_results_list[["gg_curve"]]
# detection_lims <- params$fit_results_list[["detection_lims"]]
```

## Count data used
```{r echo=FALSE}
num_cols <- as.numeric(ncol(count_data))
col_headers <- colnames(count_data)
col_headers[1] <- paste(col_headers[1], "(Gy)")

hot <- count_data %>%
  rhandsontable(width = (70 + num_cols * 50), height = "100%", colHeaders = col_headers) %>%
  hot_cols(colWidths = 50) %>%
  hot_col(c(1), format = "0.000", colWidths = 60) %>%
  hot_col(c(2), colWidths = 60) %>%
  hot_table(highlightCol = TRUE, highlightRow = TRUE)

if (num_cols > 3) {
  hot <- hot %>%
    hot_col(c(2, 3, seq(num_cols - 1, num_cols, 1)), readOnly = TRUE) %>%
    hot_col(num_cols, renderer = "
       function (instance, td, row, col, prop, value, cellProperties) {
         Handsontable.renderers.NumericRenderer.apply(this, arguments);
         if (value > 1.96) {
          td.style.background = 'pink';
         }
       }")
}

hot
```

## Results

### Fit formula
```{r echo=FALSE}
withMathJax(paste0("$$", fit_formula_tex, "$$"))
```

### Model
`r fit_model_summary`

### Coefficients
```{r echo=FALSE}
num_cols <- as.numeric(ncol(fit_coeffs))

fit_coeffs %>%
  formatC(format = "e", digits = 3) %>%
  # as.data.frame() %>%
  # dplyr::select(-statistic) %>%
  # as.matrix() %>%
  # Convert to hot and format table
  rhandsontable(width = (50 + num_cols * 100), height = "100%") %>%
  hot_cols(colWidths = 100) %>%
  hot_cols(halign = "htRight")
```

### Model-level statistics
```{r echo=FALSE}
num_cols <- as.numeric(ncol(fit_model_statistics))

fit_model_statistics %>%
  # Convert to hot and format table
  rhandsontable(width = (num_cols * 70), height = "100%") %>%
  hot_cols(colWidths = 70)
```

### Correlation matrix
```{r echo=FALSE}
num_cols <- as.numeric(ncol(fit_cor_mat))

fit_cor_mat %>%
  # Convert to hot and format table
  rhandsontable(width = (50 + num_cols * 100), height = "100%") %>%
  hot_cols(colWidths = 100) %>%
  hot_cols(format = "0.000")
```

### Variance-covariance matrix
```{r echo=FALSE}
num_cols <- as.numeric(ncol(fit_var_cov_mat))

fit_var_cov_mat %>%
  formatC(format = "e", digits = 3) %>%
  # Convert to hot and format table
  rhandsontable(width = (50 + num_cols * 100), height = "100%") %>%
  hot_cols(colWidths = 100) %>%
  hot_cols(halign = "htRight")
```

<!-- ### Detection limits -->
<!-- ```{r echo=FALSE} -->
<!-- num_cols <- 5 -->
<!-- col_headers <- c("N", "X95", "D (mGy)", "X83", "D (mGy)") -->

<!-- detection_lims %>% -->
<!--   # Convert to hot and format table -->
<!--   rhandsontable(width = (100 + num_cols * 50), height = "100%", colHeaders = col_headers) %>% -->
<!--   hot_col(c(1), readOnly = TRUE) %>% -->
<!--   hot_col(c(3, 5), format = "0.00", colWidths = 75) %>% -->
<!--   hot_cols(colWidths = 50) -->
<!-- ``` -->


### Curve plot
```{r echo=FALSE}
gg_curve
```


### Download fit results
```{r echo=FALSE}
results_list <- params$fit_results_list
results_list[["gg_curve"]] <- NULL
embed_var(results_list)
```
