---
title: "Curve fitting report"
author: "Biodose Tools"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: 
  html_document:
    theme: cosmo
params:
  fit_result: NA
  fit_coeffs: NA
  var_cov_mat: NA
  cor_mat: NA
  gg_curve: NA
---

```{r include=FALSE}
library(xfun)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{r include=FALSE}
embed_var <- function(x, ...) {
  # f = tempfile(fileext = '.rds')
  f = paste("fitting-data-", Sys.Date(), ".rds", sep = "")
  saveRDS(x, f)
  xfun::embed_file(f, ...)
}
```

### Result of curve fit
```{r echo=FALSE}
params$fit_result
```

```{r echo=FALSE}
embed_var(params$fit_result)
```

### Coefficients
```{r echo=FALSE}
params$fit_coeffs %>% 
  knitr::kable()
```

### Model-level statistics
```{r echo=FALSE}
broom::glance(params$fit_result) %>%
  select(logLik, df.null, df.residual, null.deviance, deviance, AIC, BIC) %>% 
  knitr::kable()
```

### Variance-covariance matrix
```{r echo=FALSE}
params$var_cov_mat %>% 
  knitr::kable()
```

### Correlation matrix
```{r echo=FALSE}
params$cor_mat %>% 
  knitr::kable()
```

### Plot
```{r echo=FALSE}
params$gg_curve
```

