---
title: "Dose estimation report"
author: "Biodose Tools"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: 
  # prettydoc::html_pretty:
    # theme: cayman
  html_document:
    theme: cosmo
    # css: style.css
params:
  assessment: NA
  est_doses_whole: NA
  est_doses_partial: NA
  est_frac_partial: NA
  est_mixing_prop_hetero: NA
  est_yields_hetero: NA
  est_doses_hetero: NA
  est_frac_hetero: NA
  fit_coeffs: NA
  fit_formula_tex: NA
  case_data: NA
  case_description: NA
  results_comments: NA
  gg_curve: NA
---

```{r include=FALSE}
library(xfun)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{r include=FALSE}
embed_var <- function(x, ...) {
  # f = tempfile(fileext = '.rds')
  f = paste("fitting-data-", Sys.Date(), ".rds", sep = "")
  saveRDS(x, f)
  xfun::embed_file(f, ...)
}
```

## Curve used

### Fit formula
```{r echo=FALSE}
withMathJax(paste0("$$", params$fit_formula_tex, "$$"))
```

### Coefficients
```{r echo=FALSE}
params$fit_coeffs %>% 
  rhandsontable(width = "100%", height = "100%") %>% 
  hot_cols(format = "0.000")
```



## Case data analyzed
```{r echo=FALSE}
params$case_data %>% 
  rhandsontable(width = "100%", height = "100%")
```

### Case description
`r params$case_description`


## Dose estimation results

`r if (TRUE) {"### Whole-body"}`
```{r echo=FALSE}
if (TRUE) {
  params$est_doses_whole %>%
    dplyr::select(yield) %>%
    t() %>%
    as.data.frame() %>%
    # Convert to hot and format table
    rhandsontable(width = "100%", height = "100%") %>%
    hot_cols(colWidths = 80) %>%
    hot_cols(format = "0.000")
} 
```

```{r echo=FALSE}
if (TRUE) {
  params$est_doses_whole %>%
    dplyr::select(dose) %>%
    t() %>%
    as.data.frame() %>%
    # Convert to hot and format table
    rhandsontable(width = "100%", height = "100%") %>%
    hot_cols(colWidths = 80) %>%
    hot_cols(format = "0.000")
} 
```

`r if (params$assessment == "partial") {"### Partial"}`
```{r echo=FALSE}
if (params$assessment == "partial") {
  params$est_doses_partial %>%
      dplyr::select(yield) %>%
      t() %>%
      as.data.frame() %>%
      # Fix possible NA values
      dplyr::mutate_if(is.logical, as.double) %>%
      `colnames<-`(c("lower", "estimate", "upper")) %>%
      `row.names<-`("yield") %>%
      # Convert to hot and format table
      rhandsontable(width = "100%", height = "100%") %>%
      hot_cols(colWidths = 80) %>%
      hot_cols(format = "0.000")
} 
```

```{r echo=FALSE}
if (params$assessment == "partial") {
  params$est_doses_partial %>%
    dplyr::select(dose) %>%
    t() %>%
    as.data.frame() %>%
    # Fix possible NA values
    dplyr::mutate_if(is.logical, as.double) %>%
    `colnames<-`(c("lower", "estimate", "upper")) %>%
    `row.names<-`("dose") %>%
    # Convert to hot and format table
    rhandsontable(width = "100%", height = "100%") %>%
    hot_cols(colWidths = 80) %>%
    hot_cols(format = "0.000")
} 
```

```{r echo=FALSE}
if (params$assessment == "partial") {
  params$est_frac_partial %>%
      t() %>%
      as.data.frame() %>%
      # Fix possible NA values
      dplyr::mutate_if(is.logical, as.double) %>%
      `colnames<-`(c("lower", "estimate", "upper")) %>%
      `row.names<-`("fraction") %>%
      # Convert to hot and format table
      rhandsontable(width = "100%", height = "100%") %>%
      hot_cols(colWidths = 80) %>%
      hot_cols(format = "0.000")
} 
```

`r if (params$assessment == "hetero") {"### Hetero"}`

```{r echo=FALSE}
if (params$assessment == "hetero") {
  params$est_mixing_prop_hetero %>%
      # Fix possible NA values
      dplyr::mutate_if(is.logical, as.double) %>%
      `colnames<-`(c("y_estimate", "y_std_err", "f_estimate", "f_std_err")) %>%
      `row.names<-`(c("dose1", "dose2")) %>%
      # Convert to hot and format table
      rhandsontable(width = "100%", height = "100%") %>%
      hot_cols(colWidths = 80) %>%
      hot_cols(format = "0.000")
}
```

```{r echo=FALSE}
if (params$assessment == "hetero") {
  params$est_yields_hetero %>%
    t() %>%
    as.data.frame() %>%
    # Fix possible NA values
    dplyr::mutate_if(is.logical, as.double) %>%
    `colnames<-`(c("lower", "estimate", "upper")) %>%
    `row.names<-`(c("yield1", "yield2")) %>%
    # Convert to hot and format table
    rhandsontable(width = "100%", height = "100%") %>%
    hot_cols(colWidths = 80) %>%
    hot_cols(format = "0.000")
}
```

```{r echo=FALSE}
if (params$assessment == "hetero") {
  params$est_doses_hetero %>%
      t() %>%
      as.data.frame() %>%
      # Fix possible NA values
      dplyr::mutate_if(is.logical, as.double) %>%
      `colnames<-`(c("lower", "estimate", "upper")) %>%
      `row.names<-`(c("dose1", "dose2")) %>%
      # Convert to hot and format table
      rhandsontable(width = "100%", height = "100%") %>%
      hot_cols(colWidths = 80) %>%
      hot_cols(format = "0.000")
}
```

```{r echo=FALSE}
if (params$assessment == "hetero") {
  params$est_frac_hetero %>%
      # Fix possible NA values
      dplyr::mutate_if(is.logical, as.double) %>%
      `colnames<-`(c("estimate", "std_err")) %>%
      `row.names<-`(c("dose1", "dose2")) %>%
      # Convert to hot and format table
      rhandsontable(width = "100%", height = "100%") %>%
      hot_cols(colWidths = 80) %>%
      hot_cols(format = "0.000")
}
```




### Curve plot
```{r echo=FALSE}
params$gg_curve
```

### Comments
`r params$results_comments`
