---
title: "Curve fitting report"
author: "Biodose Tools"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: 
  # prettydoc::html_pretty:
    # theme: cayman
  html_document:
    theme: cosmo
    # css: style.css
params:
  count_data: NA
  fit_result: NA
  fit_coeffs: NA
  var_cov_mat: NA
  cor_mat: NA
  fit_formula_tex: NA
  gg_curve: NA
---

```{r include=FALSE}
library(xfun)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{r include=FALSE}
embed_var <- function(x, ...) {
  # f = tempfile(fileext = '.rds')
  f = paste("fitting-data-", Sys.Date(), ".rds", sep = "")
  saveRDS(x, f)
  xfun::embed_file(f, ...)
}
```

### Count data used
```{r echo=FALSE}
params$count_data %>% 
  # knitr::kable()
  rhandsontable(width = "100%", height = "100%")
```

### Fit formula
```{r echo=FALSE}
withMathJax(paste0("$$", params$fit_formula_tex, "$$"))
```

### Coefficients
```{r echo=FALSE}
params$fit_coeffs %>% 
  # as.matrix() %>% 
  # round(digits = 3) %>% 
  # knitr::kable()
  rhandsontable(width = "100%", height = "100%") %>% 
  hot_cols(format = "0.000")
```

### Model-level statistics
```{r echo=FALSE}
broom::glance(params$fit_result) %>%
  dplyr::rename(
    df.res = df.residual,
    dev.null = null.deviance,
    dev.res = deviance
  ) %>%
  dplyr::select(logLik, dev.null, df.null, dev.res, df.res, AIC, BIC) %>%
  dplyr::mutate(dev.null = ifelse(dev.null == Inf, as.character(dev.null), dev.null)) %>%
  # round(digits = 3) %>% 
  # knitr::kable()
  rhandsontable(width = "100%", height = "100%") %>% 
  hot_cols(format = "0.000")
```

### Correlation matrix
```{r echo=FALSE}
params$cor_mat %>% 
  # round(digits = 3) %>% 
  # knitr::kable()
  rhandsontable(width = "100%", height = "100%") %>% 
  hot_cols(format = "0.000")
```

### Variance-covariance matrix
```{r echo=FALSE}
params$var_cov_mat %>% 
  formatC(format = "e", digits = 3) %>% 
  # knitr::kable()
  rhandsontable(width = "100%", height = "100%") %>%
  hot_cols(halign = "htRight")
```

### Curve plot
```{r echo=FALSE}
params$gg_curve
```


### Download fit results
```{r echo=FALSE}
embed_var(params$fit_result)
```
